env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo
    RCLONE_CONFIG_CONTENT: ENCRYPTED[2fe67cc504357d93ca53a899c03f62c577f0b08fe60751e1397a5ca8b504bf5b823c5ee26e9fa292a430cc41e89e6af2]

task:
    name: lineage
    timeout_in: 120m
    container:
        image: koswu/aosp-buildenv
        cpu: 8
        memory: 32G
        greedy: true
    init_repo_script:
        - mkdir /tmp/rom && cd /tmp/rom
        - echo "clone lineage source code"
        - repo init --depth=1 -u git://github.com/LineageOS/android.git -b lineage-18.1
    copy_manifests_script:
        - cp -r local_manifests /tmp/rom/.repo/
    setup_rclone_script:
        - mkdir -p ~/.config/rclone
        - echo -e $RCLONE_CONFIG_CONTENT > ~/.config/rclone/rclone.conf
    test_rclone_script:
        - echo 111 > /tmp/test
        - "rclone copy /tmp/test onedrive:"
    sync_repo_script:
        - cd /tmp/rom
        - repo sync -c
    build_script:
        - cd /tmp/rom
        - source build/envsetup.sh
        - lunch lineage_vangogh-user
        - mka bacon
    upload_script:
        - "rclone copy /tmp/rom/out/target/product/*/lineage-* onedrive:"
