env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

task:
    name: lineage
    timeout_in: 120m
    container:
        image: koswu/aosp-buildenv
        cpu: 4
        memory: 16G
        greedy: true
    sync_script:
      - sh install_repo.sh
      - echo "clone lineage source code"
      - mkdir -p /tmp/rom && cd /tmp/rom
      - repo init --depth=1 -u git://github.com/LineageOS/android.git -b lineage-18.1 
      - repo sync -c --force-sync
    copy_manifests:
      - mkdir /tmp/rom
      - cp local_manifests /tmp/rom/.repo