env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

task:
    name: lineage
    timeout_in: 120m
    container:
        image: koswu/aosp-buildenv
        cpu: 10
        memory: 16G
    sync_script:
      - sh sync.sh
    copy_manifests:
      - mkdir /tmp/rom
      - cp local_manifests /tmp/rom/.repo