env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo
    RCLONE_CONFIG: ENCRYPTED[40b7d81aacdf1e8c91dd55077f16d75405099ff4c02ae05ae3b3a75aef469f7e2a9293284d5c45a64bdafdb12e4f8325]

task:
    name: lineage
    timeout_in: 120m
    container:
        image: koswu/aosp-buildenv
        cpu: 4
        memory: 16G
        greedy: true
    init_repo_script:
        - mkdir /tmp/rom && cd /tmp/rom
        - echo "clone lineage source code"
        - repo init --depth=1 -u git://github.com/LineageOS/android.git -b lineage-18.1
    copy_manifests_script:
        - cp -r local_manifests /tmp/rom/.repo/
    setup_rclone_script:
        - mkdir -p ~/.config/rclone
        - echo $RCLONE_CONFIG > ~/.config/rclone/rclone.conf
    test_rclone_script:
        - echo 111 > ./test
        - "rclone copy ./test onedrive:"
    sync_repo_script:
        - repo sync -c
    build_script:
        - source build/envsetup.sh
        - lunch lineage lineage_vangogh-user
        - mka bacon
    upload_script:
        - "rclone copy ./out/target/product/*/lineage-* onedrive:"
